server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://192.168.150.129:3306/gmall?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application:
      name: cart-service
    registry:
      protocol: zookeeper
      address: 192.168.150.129:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
  redis:
    host: 192.168.150.129
    port: 6379
    timeout: 20000
logging:
  level:
    root: info