server:
  port: 8009
spring:
  dubbo:
    application:
      name: passport-web
    registry:
      protocol: zookeeper
      address: 192.168.150.129:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
    consumer:
      timeout: 10000
      check: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  level:
    root: info

token:
  key: ATGUIGU_GMALL_KEY