server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.150.129:3306/gmall?useSSL=false&serverTimezone=GMT%2B8
  dubbo:
    application:
      name: usermanage
    registry:
      protocol: zookeeper
      address: 192.168.150.129:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
  redis:
    host: 192.168.150.129
    port: 6379
    timeout: 20000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

